
# Nombre de la app
spring.application.name=gestor-tareas

# Conexión a PostgreSQL (debe coincidir con tu docker-compose.yml)
spring.datasource.url=jdbc:postgresql://localhost:5432/gestor_tareas
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway (migraciones)
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.jpa.open-in-view=false